### ISSUE TITLE
Remove usage of a classifier

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/fuse-rest-http-booster#25]
based on RHOAR team, the use of the classifier should be nowadays avoided. They were initially using as workaround. It seems that they are now using another workaround which is "cleaner". It allows to stay closer to an out of the box SpringBoot project and then to have it working with [odo](https://github.com/redhat-developer/odo)

The other workaround is to specific a name on the maven-failsafe-plugin classes-directory, see https://github.com/snowdrop/spring-boot-http-booster/blob/a5b271f3bf1356d5e46b75ef7d463ea7d462c1a9/pom.xml#L194 and notice that there is no classifier https://github.com/snowdrop/spring-boot-http-booster/blob/a5b271f3bf1356d5e46b75ef7d463ea7d462c1a9/pom.xml#L168-L178
See the commit which did that https://github.com/snowdrop/spring-boot-http-booster/commit/1eac1c2780968a48a0aeceb9c7bb5b712cde72a2

@valdar do you know if it can cause trouble to follow the same way? Any opinions?

**Comment by apupier** [comment]
created https://issues.jboss.org/browse/ENTESB-9846 as it applies to all quickstarts/boosters/examples

**Comment by bfitzpat** [comment]
To clarify this issue @apupier , are you suggesting we remove the classifier as defined here? - https://github.com/jboss-fuse/fuse-rest-http-booster/blob/824ceb03269309551509b1b3a0167446e596078d/pom.xml#L170

**Comment by apupier** [comment]
I suggest to follow what has been done in snowdrop project snowdrop/spring-boot-http-booster@1eac1c2
I.e. removing the classifier and configuring the maven-failsafe-plugin

**Comment by bfitzpat** [comment]
Created https://github.com/jboss-fuse/fuse-rest-http-booster/pull/27
