### ISSUE TITLE
On redhat version, io.fabric8:openshift-client is specified 2 times with different scope

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/fuse-rest-http-booster#30]
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.fabric8:openshift-client:jar -> duplicate declaration of version (?) @ line 123, column 17

https://github.com/jboss-fuse/fuse-rest-http-booster/blob/07d1c288553091e42e09b6acf563aeeec70a3a65/pom.xml#L109-L113

https://github.com/jboss-fuse/fuse-rest-http-booster/blob/07d1c288553091e42e09b6acf563aeeec70a3a65/pom.xml#L136-L139

**Comment by valdar** [comment]
fixed in https://github.com/jboss-fuse/fuse-rest-http-booster/commit/390e8b1504e9248e476b7caa29a1101033c136fd
